backend:
  name: git-gateway
  branch: main/admin
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
